max_locations_per_request: 1000
datasets:
# A small testing dataset is included in the repo.
- name: test-dataset
  path: tests/data/datasets/test-etopo1-resampled-1deg/
# EU-DEM
- name: eudem25m
  path: data/eudem/
  filename_epsg: 3035
  filename_tile_size: 1000000
# BKG-DGM200
- name: bkg200m
  path: data/bkg-dgm200/
# BKG-DGM10
- name: bkg10m
  path: data/bkg-dgm10/
  filename_epsg: 3044
  filename_tile_size: 20000
